Added info about two flags (quiet/dry-run)
ivandokov/phockup pull request #105
Opened 2021-03-28 17:23 UTC by roykrikke

Readme updated on request. I have also taken the liberty of adding dry-run flag description.

2021-03-28 18:22 UTC, ivandokov requested changes

2021-03-28 18:22 UTC, ivandokov commented on readme.md
> +If you want view the version of phockup use the flag `-v | --version`.
If you want **to** view...

2021-03-28 18:43 UTC, roykrikke commented on readme.md
> +If you want view the version of phockup use the flag `-v | --version`.
Done

2021-03-28 18:45 UTC, roykrikke commented
I noticed that the latest update did not automatically come with "snap". Is that correct behavior?

2021-03-30 09:14 UTC, ivandokov commented
Yes it is correct as new versions are deployed only by new tags.

2021-03-30 09:14 UTC, merged