Added the --no-unknown flag to ignore these, fixes #79
ivandokov/phockup pull request #116
Opened 2021-07-21 09:46 UTC by frafall

Added the command line flag -n or --no-unknown to ignore processing of files that would have ended up in the 'unknown' folder.

2021-08-08 20:26 UTC, inverse approved these changes

2021-08-13 17:38 UTC, roykrikke commented
This is a nice addition. But I am missing the necessary tests (pytest) to test this feature automatically,

2021-08-22 14:18 UTC, ivandokov requested changes
First, I'd like to thank you for the contribution! 

I have to agree we need tests for this new functionality.

But also I have some concerns about something that's not even a topic of the PR - delete duplicates feature.
It has to be in a separate PR and I don't think we shouldn't have this functionality at all. The source directory should always remain untouched by the tool. That's a very crucial thing for this software - we do not mess up the source. And we already have the duplicate check for the target directory so in most cases you will not have duplicates in the end.

2021-10-02 21:07 UTC, ivandokov commented
@frafall I'm going to close this PR now due to inactivity and let someone else tackle this issue, unless you want to make the requested changes and in that case I can re-open it.

2021-10-02 21:07 UTC, closed without merging