Feature added: Issue #65
ivandokov/phockup pull request #204
Opened 2023-07-01 12:05 UTC by AamerShareef

Added feature - Issue #65.

### New flags added 🥳 
**--filename_add_original** (or) **-ao** : Adds the original filename to the new filename
**--filename_suffix** : Adds a custom suffix to the new filename.

### Sample Output:

```
1227c98e03af:/opt/phockup# ./phockup.py /mnt/test_input/ /mnt/test_output/ -y --filename_add_original --filename_suffix=NIKON

[2023-07-01 12:02:01] - [WARNING] - Dry-run phockup (does a trial run with no permanent changes)...
[2023-07-01 12:02:01] - [INFO] - /mnt/test_input/DSCF1904.JPG => /mnt/test_output/2023/05/18/20230518-041043_DSCF1904_NIKON.JPG
[2023-07-01 12:02:01] - [INFO] - Processed 1 files in 0.10 seconds. Average Throughput: 9.93 files/second
[2023-07-01 12:02:01] - [INFO] - Would have copied 1 files.
```

2023-07-02 10:16 UTC, AamerShareef commented
This is for issue #65 not 63 :)

2023-07-11 07:43 UTC, ivandokov commented
Please add tests for the new features.

2023-07-11 07:46 UTC, ivandokov requested changes
Please take a look at the comments I left and the tests.

2023-07-11 07:46 UTC, ivandokov commented on phockup.py
> +       '--filename_suffix',
Please change the `_` with a `-`

2023-07-11 07:46 UTC, ivandokov commented on phockup.py
> +        '--filename_add_original',
Please change the `_` with a `-`

2023-07-11 07:46 UTC, ivandokov commented on src/phockup.py
> +                #debug
Please remove this comment

2023-07-11 07:46 UTC, ivandokov commented on src/phockup.py
> +                # print(target_filename)
Please remove this comment

2023-11-13 09:08 UTC, ivandokov commented
I'm closing this PR as it needs to be updated to fit the current state of the code as it has conflicts. Also some of the features are already merged.

2023-11-13 09:08 UTC, closed without merging